version: '3.9'

networks:
  trainee_network:
    driver: bridge

services:
  testapp_auth:
    build:
      context: .
      dockerfile: ./srv/app/Dockerfile
    volumes:
      - .:/app
    networks:
      - trainee_network