version: '3.9'

networks:
  trainee_network:
    driver: bridge

services:
  testapp:
    environment:
      ENVIRONMENT: 'testing'
    build:
      context: .
      dockerfile: ./srv/celery/Dockerfile
    volumes:
      - .:/app
    networks:
      - trainee_network