version: '3.9'

networks:
  trainee_network:
    driver: bridge

services:
  app_auth:
    restart: always
    build:
      context: .
      dockerfile: ./srv/app/Dockerfile
    command: gunicorn src.config.wsgi:application --bind 0.0.0.0:8000 --reload --workers=3 --timeout=120
    volumes:
      - .:/app
      - ./static/:/static
    ports:
      - 8000:8000
    expose:
      - 8000
    depends_on:
      - db
    networks:
      - trainee_network

  webserver:
    build: ./srv/webserver
    restart: always
    volumes:
      - ./static/:/static
      - ./srv/webserver/nginx.conf:/ect/nginx/nginx.conf
      - ./srv/webserver/conf.d/:/etc/nginx/conf.d/
    ports:
      - 1337:80
    depends_on:
      - app_auth
    networks:
      - trainee_network

  rabbit:
    restart: always
    image: rabbitmq:3.9.8
    environment:
      RABBITMQ_NODENAME: "rabbit@localhost"
      RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
      RABBITMQ_DEFAULT_USER: "rabbitmq"
      RABBITMQ_DEFAULT_PASS: "rabbitmq"
      RABBITMQ_DEFAULT_VHOST: "/"
    ports:
      - "5672:5672"
    networks:
      - trainee_network

  celery:
    restart: always
    build: .
    volumes:
      - .:/app
    environment:
      DJANGO_SETTINGS_MODULE: "{APP}.settings.docker"
    ports:
      - "5555:5555"
    command: bash -c "
      rm -rf /tmp/celery*.pid &
      python -m celery multi start --app={APP} --pidfile=/tmp/%n.pid --logfile=/app/logs/celery/%n.log 4 -c 4 -Q:1 dispatch -Q:2 process_item -Q:3 network -c:4 1 -Q:4 celery -E &&
      python -m celery -A {APP} beat --pidfile=/tmp/celerybeat.pid -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler --detach
    links:
      - rabbit
    depends_on:
      - rabbit
    networks:
      - trainee_network

  db:
    image: postgres:12.8
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: "${DATABASE_USER}"
      POSTGRES_PASSWORD: "${DATABASE_PASSWORD}"
      POSTGRES_DB: "${DATABASE_NAME}"
    ports:
      - 5432:5432
    networks:
      - trainee_network

volumes:
  postgres_data: