# Generated by Django 3.2.7 on 2021-09-23 08:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(help_text='Users first name', max_length=30)),
                ('last_name', models.CharField(help_text='Users last name', max_length=40)),
                ('email', models.EmailField(help_text='Users email', max_length=254, unique=True)),
                ('age', models.IntegerField()),
                ('password', models.CharField(help_text='Users password', max_length=64)),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
