# Generated by Django 3.2.7 on 2021-09-23 14:15

from django.db import migrations, models
import src.accounts.validators


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.PositiveIntegerField(blank=True, help_text='Users age', validators=[src.accounts.validators.validate_age]),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, help_text='Users first name', max_length=30, validators=[src.accounts.validators.validate_name]),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, help_text='Users last name', max_length=40, validators=[src.accounts.validators.validate_name]),
        ),
    ]
