# Generated by Django 3.2.7 on 2021-09-23 14:17

from django.db import migrations, models
import src.accounts.validators


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210923_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.PositiveIntegerField(help_text='Users age', validators=[src.accounts.validators.validate_age]),
        ),
    ]
