# Generated by Django 3.2.7 on 2021-10-19 07:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FilesStorage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('is_alive', models.BooleanField(default=True)),
                ('type', models.CharField(choices=[('temp', 'Temporary Storage'), ('permanent', 'Permanent Storage')], max_length=32)),
                ('destination', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'files_storage',
            },
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('is_alive', models.BooleanField(default=True)),
                ('destination', models.CharField(max_length=256)),
                ('name', models.CharField(max_length=256)),
                ('description', models.TextField()),
                ('type', models.CharField(max_length=10)),
                ('size', models.BigIntegerField()),
                ('hash', models.CharField(max_length=512)),
                ('storage', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='files.filesstorage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'file',
            },
        ),
    ]
