# Generated by Django 3.2.7 on 2021-11-30 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_create_storage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='type',
            field=models.CharField(max_length=128),
        ),
    ]
